version: '3'
services:
  redis-server:
    image: 'redis'
    ports:
      - '6379:6379'
  web1:
    restart: on-failure
    build: ./web1
    ports:
      - "8081:8080"
  web2:
    restart: on-failure
    build: ./web2
    ports:
      - "8082:8080"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
